import * as T from 'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';
const stage=document.getElementById('stage'),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(1);renderer.setSize(1280,720);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.append(renderer.domElement);
const cam=new T.PerspectiveCamera(35,640/720,.02,30),center=new T.Vector3(0,1.1,0);let view='side',phase=0,clip='Rest',playing=false,last=performance.now(),panels;
function make(asset){const scene=new T.Scene();scene.background=new T.Color('#ccd2c8');scene.add(new T.HemisphereLight(0xf6f7ff,0x7b816c,2.1));const light=new T.DirectionalLight(0xfff2dd,2.8);light.position.set(-3,7,4);scene.add(light);const fill=new T.DirectionalLight(0xe7efff,.9);fill.position.set(4,3,-2);scene.add(fill);const floor=new T.Mesh(new T.PlaneGeometry(20,20),new T.MeshStandardMaterial({color:'#aeb6a8',roughness:1}));floor.rotation.x=-Math.PI/2;scene.add(floor);const root=asset.scene;scene.add(root);root.updateMatrixWorld(true);const objects=[],meshes=[];root.traverse(o=>{objects.push(o);o.userData.packedRest={p:o.position.clone(),q:o.quaternion.clone(),s:o.scale.clone()};if(o.isSkinnedMesh){o.frustumCulled=false;meshes.push(o)}});meshes.sort((a,b)=>a.geometry.attributes.position.count-b.geometry.attributes.position.count);return{scene,root,objects,meshes,mixer:new T.AnimationMixer(root),clips:asset.animations,action:null};}
function pose(p,name,f){p.mixer.stopAllAction();for(const o of p.objects){const r=o.userData.packedRest;o.position.copy(r.p);o.quaternion.copy(r.q);o.scale.copy(r.s)}p.action=null;if(name!=='Rest'){const c=T.AnimationClip.findByName(p.clips,name);if(!c)throw Error('Missing clip '+name);p.action=p.mixer.clipAction(c);p.action.play();p.mixer.setTime(f*c.duration)}p.root.updateMatrixWorld(true);for(const m of p.meshes)m.skeleton.update();}
function camera(){const yaw=view==='side'?-Math.PI/2:-.75,pitch=view==='side'?.065:.12;cam.position.copy(center).add(new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(6.5));cam.lookAt(center)}
function draw(){if(!panels)return;camera();renderer.setRenderTarget(null);renderer.setScissorTest(true);for(const[i,p]of panels.entries()){renderer.setViewport(i*640,0,640,720);renderer.setScissor(i*640,0,640,720);renderer.render(p.scene,cam)}renderer.setScissorTest(false)}
const target=new T.WebGLRenderTarget(640,720),pixels=[new Uint8Array(640*720*4),new Uint8Array(640*720*4)],points=[new T.Vector3(),new T.Vector3()];
function compare(name,f,v){clip=name;phase=f;view=v;for(const p of panels)pose(p,name,f);camera();let maxNodeMatrixDifference=0,allFinite=true;const meshRows=[];if(panels[0].objects.length!==panels[1].objects.length)throw Error('Object count differs');for(let i=0;i<panels[0].objects.length;i++){const a=panels[0].objects[i],b=panels[1].objects[i];if(a.name!==b.name)throw Error('Object names/order differ');for(let c=0;c<16;c++){allFinite&&=Number.isFinite(a.matrixWorld.elements[c])&&Number.isFinite(b.matrixWorld.elements[c]);maxNodeMatrixDifference=Math.max(maxNodeMatrixDifference,Math.abs(a.matrixWorld.elements[c]-b.matrixWorld.elements[c]))}}
for(let mi=0;mi<panels[0].meshes.length;mi++){const a=panels[0].meshes[mi],b=panels[1].meshes[mi],count=a.geometry.attributes.position.count;if(a.name!==b.name||count!==b.geometry.attributes.position.count)throw Error('Mesh differs');let max=0;const min=[Infinity,Infinity];for(let i=0;i<count;i++){a.getVertexPosition(i,points[0]);points[0].applyMatrix4(a.matrixWorld);b.getVertexPosition(i,points[1]);points[1].applyMatrix4(b.matrixWorld);max=Math.max(max,points[0].distanceTo(points[1]));for(let k=0;k<2;k++){min[k]=Math.min(min[k],points[k].y);allFinite&&=points[k].toArray().every(Number.isFinite)}}meshRows.push({name:a.name,vertices:count,sourceJoints:a.skeleton.bones.length,packedJoints:b.skeleton.bones.length,maxSkinnedWorldPointDifferenceM:max,minY:min})}
cam.aspect=640/720;cam.updateProjectionMatrix();renderer.setScissorTest(false);renderer.setRenderTarget(target);renderer.setViewport(0,0,640,720);for(let i=0;i<2;i++){renderer.render(panels[i].scene,cam);renderer.readRenderTargetPixels(target,0,0,640,720,pixels[i])}let differingChannels=0,maxChannelDifference=0,sum=0;const differingPixels=[];for(let i=0;i<pixels[0].length;i++){const d=Math.abs(pixels[0][i]-pixels[1][i]);if(d){differingChannels++;const pixel=Math.floor(i/4);if(differingPixels.length<20&&!differingPixels.some(p=>p.pixel===pixel))differingPixels.push({pixel,x:pixel%640,y:Math.floor(pixel/640),source:Array.from(pixels[0].slice(pixel*4,pixel*4+4)),packed:Array.from(pixels[1].slice(pixel*4,pixel*4+4))})}maxChannelDifference=Math.max(maxChannelDifference,d);sum+=d}renderer.setRenderTarget(null);draw();return{clip:name,phase:f,view:v,objectCount:panels[0].objects.length,maxNodeMatrixDifference,allFinite,meshes:meshRows,render:{width:640,height:720,rgbaChannels:pixels[0].length,differingPixels,differingChannels,maxChannelDifference,meanAbsoluteChannelDifference:sum/pixels[0].length,method:'Same camera/lights/materials/floor, non-MSAA RGBA8 render target, actual GLTF GPU skinning, paired readRenderTargetPixels.'}};}
window.packedPilot={ready:false,compare,stableOrder(){for(const p of panels){p.scene.children.find(o=>o.isMesh).renderOrder=-1;for(const[i,m]of p.meshes.entries())m.renderOrder=i+1}}};
try{const assets=await Promise.all([new GLTFLoader().loadAsync('../native-bay-sporthorse-head-kit/model.glb'),new GLTFLoader().loadAsync(new URLSearchParams(location.search).get('control')==='source'?'../native-bay-sporthorse-head-kit/model.glb':'./model.glb')]);panels=assets.map(make);window.packedPilot.ready=true;for(const p of panels)pose(p,'Rest',0);draw();document.getElementById('status').textContent='Both native 677-joint assets loaded. Lossless runtime package comparison.'}catch(e){document.getElementById('status').textContent=e.message;console.error(e)}
document.getElementById('clip').onchange=e=>{clip=e.target.value;phase=0;for(const p of panels)pose(p,clip,phase);draw()};document.getElementById('side').onclick=()=>{view='side';draw()};document.getElementById('quarter').onclick=()=>{view='quarter';draw()};document.getElementById('play').onclick=()=>{playing=!playing;document.getElementById('play').textContent=playing?'Pause':'Play'};
function tick(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(playing&&panels&&clip!=='Rest'){const c=T.AnimationClip.findByName(panels[0].clips,clip);phase=(phase+dt/c.duration)%1;for(const p of panels)pose(p,clip,phase);draw()}requestAnimationFrame(tick)}requestAnimationFrame(tick);
