import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {createNativeHorseMotion} from '../../../assets/native-horse-motion.js?v=reference-hoof-pilot-1';
import {NATIVE_BREED_PROFILES} from '../../../assets/native-breed-profiles.js?v=reference-hoof-pilot-1';
const ID=new URLSearchParams(location.search).get('horse')||'bay-western',TARGET={'white-western':'white','bay-western':'bay','bay-sporthorse-native':'sporthorse'}[ID],FILES={original:'../../'+({'white':'native-white-head-kit','bay':'native-bay-head-kit','sporthorse':'native-bay-sporthorse-packed-kit'}[TARGET])+'/model.glb',shipped:'../../native-front-hoof-kit/'+TARGET+'/model.glb',pilot:'./model.glb'},MASKS=(await(await fetch('../config.json')).json())[ID].footMasks;
const stage=document.querySelector('#stage'),status=document.querySelector('#status');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#34443b');stage.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.01,60);scene.add(new THREE.HemisphereLight(0xe8f0ff,0x514237,2));const key=new THREE.DirectionalLight(0xfff0dc,3);key.position.set(4,7,5);scene.add(key);const fill=new THREE.DirectionalLight(0xdbe7ff,1.4);fill.position.set(-4,4,-4);scene.add(fill);scene.add(new THREE.GridHelper(10,20));const floor=new THREE.Mesh(new THREE.PlaneGeometry(24,24),new THREE.MeshStandardMaterial({color:0x455547,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.004;scene.add(floor);
const rigs={},v=new THREE.Vector3(),gaits={walk:'Target Native Walk Rollover',trot:'Target Native Trot',canterLeft:'Target Native Canter Left',canterRight:'Target Native Canter Right'};
let masks,gait='trot',phase=0,active='pilot',playing=true,last=0;
function sync(){scene.updateMatrixWorld(true);for(const r of Object.values(rigs))for(const m of r.meshes)m.skeleton.update();}
function render(){sync();renderer.render(scene,camera);}
function resize(){renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();render();}
function select(name){active=name;for(const[n,r]of Object.entries(rigs))r.actor.visible=n===name;render();}
function view(name){if(name==='close'){camera.position.set(2.25,.85,.5);camera.lookAt(.04,.45,.5);}else if(name==='quarter'){camera.position.set(4.4,2.5,4.4);camera.lookAt(0,1.05,.1);}else{camera.position.set(5.3,2.1,.1);camera.lookAt(0,1.05,.1);}render();}
function point(mesh,i){mesh.getVertexPosition(i,v);return v.applyMatrix4(mesh.matrixWorld).clone();}
function patch(r,ids){let min=Infinity,max=-Infinity;const mean=new THREE.Vector3();for(const i of ids){const p=point(r.body,i);min=Math.min(min,p.y);max=Math.max(max,p.y);mean.add(p);}return {minY:min,maxY:max,center:mean.divideScalar(ids.length).toArray()};}
function bend(a,b){return Math.atan2(a.z*b.y-a.y*b.z,a.y*b.y+a.z*b.z)*180/Math.PI;}
function inspect(full=false){const result={phase,gait,rigs:{}};
 for(const[n,r]of Object.entries(rigs)){const feet={};for(const[k,m]of Object.entries(masks)){feet[k]={whole:patch(r,m.wholeVertices),sole:patch(r,m.vertices),toe:patch(r,m.toeVertices),heel:patch(r,m.heelVertices)};if(k==='FL'||k==='FR'){const ns=k==='FL'?['hand_l_0206','fingers_01_l_0187','fingers_02_l_0208']:['hand_r_0272','fingers_01_r_0273','fingers_02_r_0274'],p=ns.map(n=>new THREE.Vector3().setFromMatrixPosition(r.bones[n].matrixWorld)),cannon=p[1].clone().sub(p[0]),pastern=p[2].clone().sub(p[1]),toe=feet[k].toe.center,heel=feet[k].heel.center,solePitch=Math.atan2(toe[1]-heel[1],toe[2]-heel[2])*180/Math.PI;feet[k].fetlockBendDegrees=bend(cannon,pastern)-r.rest[k].bend;feet[k].solePitchDegrees=solePitch-r.rest[k].pitch;feet[k].coffinLikeBendDegrees=solePitch+Math.atan2(-pastern.z,-pastern.y)*180/Math.PI-r.rest[k].coffin;}}
 let bodyMinY=null;if(full){bodyMinY=Infinity;for(let i=0;i<r.body.geometry.attributes.position.count;i++)bodyMinY=Math.min(bodyMinY,point(r.body,i).y);}
 result.rigs[n]={feet,bodyMinY,finite:Object.values(r.bones).every(b=>b.matrixWorld.elements.every(Number.isFinite)),jointCount:Object.keys(r.bones).length,state:r.motion.snapshot()};
 }
 const protectedChanges={};for(const name of ['shipped','pilot']){let matrix=0,local=0,skin=0;const a=rigs.original,b=rigs[name];for(const[n,bone]of Object.entries(a.bones)){if(!a.affected.has(n))matrix=Math.max(matrix,...bone.matrixWorld.elements.map((x,i)=>Math.abs(x-b.bones[n].matrixWorld.elements[i])));if(!a.changed.has(n))local=Math.max(local,bone.position.distanceTo(b.bones[n].position),...bone.quaternion.toArray().map((x,i)=>Math.abs(x-b.bones[n].quaternion.toArray()[i])),bone.scale.distanceTo(b.bones[n].scale));}
 for(let j=0;j<a.meshes.length;j++){const ma=a.meshes[j],mb=b.meshes[j],ids=a.protectedVertices[j],total=ids.length;for(let i=0;i<total;i+=full?1:Math.max(1,Math.floor(total/64))){const id=ids?ids[i]:i;skin=Math.max(skin,point(ma,id).distanceTo(point(mb,id)));}}
 protectedChanges[name]={matrix,local,skin};}result.protectedChanges=protectedChanges;return result;
}
function step(dt){for(const r of Object.values(rigs))r.motion.update(dt,{rate:1});phase=rigs.pilot.motion.snapshot().phase01;document.querySelector('#phase').value=phase;sync();}
function seek(p){for(const r of Object.values(rigs)){const a=r.motion.mixer._actions.find(a=>a.getClip().name===gaits[gait]);a.time=p*a.getClip().duration;r.motion.update(0,{rate:1});}phase=((p%1)+1)%1;document.querySelector('#phase').value=phase;render();return inspect();}
function setGait(name){gait=name;for(const r of Object.values(rigs)){r.motion.reset();r.motion.set(name);r.motion.update(.2,{rate:1});}seek(0);return inspect();}
try{masks=MASKS;for(const[name,file,flex]of [['original',FILES.original,false],['shipped',FILES.shipped,true],['pilot',FILES.pilot,true]]){const asset=await new GLTFLoader().loadAsync(file),root=asset.scene,actor=new THREE.Group(),bones={},meshes=[];actor.position.fromArray(NATIVE_BREED_PROFILES[ID].nativeTranslation);actor.add(root);scene.add(actor);root.traverse(o=>{if(o.isBone)bones[o.name]=o;if(o.isSkinnedMesh)meshes.push(o)});const profile={...NATIVE_BREED_PROFILES[ID],nativeHoofFlex:flex};const r={root,actor,bones,meshes,profile,clips:asset.animations,body:meshes.find(o=>o.geometry.attributes.position.count===16159),rest:{},changed:new Set(['clavicle_l_0203','upperarm_l_0204','lowerarm_l_0205','hand_l_0206','fingers_01_l_0187','fingers_02_l_0208','clavicle_r_0269','upperarm_r_0270','lowerarm_r_0271','hand_r_0272','fingers_01_r_0273','fingers_02_r_0274']),affected:new Set(),unaffectedBody:[]};for(const n of r.changed)bones[n].traverse(o=>{if(o.isBone)r.affected.add(o.name)});const I=r.body.geometry.attributes.skinIndex,W=r.body.geometry.attributes.skinWeight;for(let i=0;i<W.count;i++){let changed=false;for(let c=0;c<4;c++)if(W.getComponent(i,c)>0&&r.affected.has(r.body.skeleton.bones[I.getComponent(i,c)].name))changed=true;if(!changed)r.unaffectedBody.push(i);}r.protectedVertices=meshes.map(m=>{const si=m.geometry.attributes.skinIndex,sw=m.geometry.attributes.skinWeight,out=[];for(let i=0;i<sw.count;i++){let altered=false;for(let c=0;c<4;c++)if(sw.getComponent(i,c)>0&&r.affected.has(m.skeleton.bones[si.getComponent(i,c)].name))altered=true;if(!altered)out.push(i);}return out;});rigs[name]=r;}
 sync();for(const r of Object.values(rigs))for(const k of ['FL','FR']){const ns=k==='FL'?['hand_l_0206','fingers_01_l_0187','fingers_02_l_0208']:['hand_r_0272','fingers_01_r_0273','fingers_02_r_0274'],p=ns.map(n=>new THREE.Vector3().setFromMatrixPosition(r.bones[n].matrixWorld)),cannon=p[1].clone().sub(p[0]),pastern=p[2].clone().sub(p[1]),toe=patch(r,masks[k].toeVertices).center,heel=patch(r,masks[k].heelVertices).center,pitch=Math.atan2(toe[1]-heel[1],toe[2]-heel[2])*180/Math.PI;r.rest[k]={bend:bend(cannon,pastern),pitch,coffin:pitch+Math.atan2(-pastern.z,-pastern.y)*180/Math.PI};}
 for(const r of Object.values(rigs))r.motion=createNativeHorseMotion({THREE,root:r.root,clips:r.clips,profile:r.profile});
 window.visibleHoofPilot={THREE,rigs,masks,renderer,scene,camera,step,seek,setGait,select,view,render,inspect,setPlaying(value){playing=value;last=0;},get phase(){return phase;},get gait(){return gait;}};setGait('trot');select('pilot');view('side');resize();status.textContent='One source-informed pilot · current ground-clearance gate';
}catch(e){window.visibleHoofPilotError=String(e.stack||e);status.textContent=String(e);console.error(e);}
document.querySelector('#gait').onchange=e=>setGait(e.target.value);document.querySelector('#play').onclick=()=>{playing=!playing;document.querySelector('#play').textContent=playing?'Pause':'Play';};document.querySelector('#phase').oninput=e=>{playing=false;seek(Number(e.target.value));};for(const b of document.querySelectorAll('[data-model]'))b.onclick=()=>select(b.dataset.model);for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>view(b.dataset.view);window.addEventListener('resize',resize);
function frame(t){const dt=last?Math.min((t-last)/1000,.05):0;last=t;if(playing&&window.visibleHoofPilot){step(dt);render();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
