import {readFile,writeFile,mkdir,readdir,stat,copyFile,rm,access} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {build} from 'esbuild';

const mobile=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),root=path.dirname(mobile),out=path.join(mobile,'www');
const spec=JSON.parse(await readFile(path.join(mobile,'runtime-assets.json'),'utf8'));
const hash=data=>createHash('sha256').update(data).digest('hex');
const rows=[];
try{await access(out);await access(path.join(out,'.meadowlark-generated'));await rm(out,{recursive:true});}catch(error){if(error.code!=='ENOENT')throw error;try{await access(out);throw Error('Refusing to replace an unmarked mobile/www directory');}catch(inner){if(inner.code!=='ENOENT')throw inner;}}
await mkdir(out,{recursive:true});await writeFile(path.join(out,'.meadowlark-generated'),'Generated by mobile/scripts/stage.mjs\n');
function storageCalls(code){return code.replace(/\b(?:window\.)?localStorage\b/g,'window.MeadowlarkNative.storage').replaceAll('location.replace(location.pathname);','void window.MeadowlarkNative.reload();');}
async function copy(relative,expected){
 const source=path.resolve(root,relative);if(!source.startsWith(root+path.sep))throw Error('Asset escapes the source tree: '+relative);
 let data=await readFile(source);const sourceHash=hash(data);
 if(expected&&sourceHash!==expected)throw Error('Approved asset changed: '+relative+'; expected '+expected+', found '+sourceHash);
 let transformed=false;
 if(/\.m?js$/.test(relative)&&!relative.includes('/vendor/')){
  let code=storageCalls(data.toString());
  // Keep import and confirmed reset reloads behind the durable write barrier.
  if(relative==='assets/features/account-economy.js')code=code.replaceAll('window.MeadowlarkNative.storage.removeItem(S.KEY)','window.MeadowlarkNative.storage.clear()').replaceAll('THIS browser','this device');
  transformed=code!==data.toString();data=Buffer.from(code);
 }
 const dest=path.join(out,relative);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,data);
 rows.push({path:relative,bytes:data.length,sha256:hash(data),sourceSha256:sourceHash,transformed});
}
async function walk(relative){
 for(const entry of (await readdir(path.join(root,relative),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){
  const file=path.posix.join(relative,entry.name);if(entry.isSymbolicLink())throw Error('Unexpected asset symlink: '+file);
  if(entry.isDirectory())await walk(file);else if(entry.isFile()&&!spec.excludedExtensions.includes(path.extname(file)))await copy(file);
 }
}
for(const directory of spec.roots)await walk(directory);
for(const file of spec.rootFiles)await copy(file);
for(const item of spec.reviewFiles)await copy(item.path,item.sha256);

let html=await readFile(path.join(root,'ranch3d.html'),'utf8');
const originalHtmlHash=hash(html);
html=storageCalls(html);
const social=/const SOCIAL\s*=\s*[^;]+;/g;
if([...html.matchAll(social)].length!==1)throw Error('SOCIAL declaration changed; review native staging integration');
html=html.replace(social,'const SOCIAL=false; // Native development edition stays offline.');
const qualityDefault="let quality=(save&&save.quality)||'high';";
if(!html.includes(qualityDefault))throw Error('Graphics default changed; review native preset selection');
html=html.replace(qualityDefault,"let quality=(save&&save.quality)||'medium'; // Native first-run default; retain the saved setting.");
html=html.replaceAll('window.MeadowlarkNative.storage.removeItem(SAVE_KEY)','window.MeadowlarkNative.storage.clear()');
const runner='runner.textContent=src.textContent;';
if(!html.includes(runner))throw Error('Game startup runner changed; native hydration must be reviewed');
html=html.replace(runner,"runner.textContent='await window.MeadowlarkNative.ready;\\n'+src.textContent;");
html=html.replace('<script id="gameModule" type="text/plain">','<script src="native-bootstrap.js"></script>\n<script id="gameModule" type="text/plain">');
const featureLoop='for(const f of FEATURES){';
if(!html.includes(featureLoop))throw Error('Feature installation changed; native social scope must be reviewed');
html=html.replace(featureLoop,"for(const f of FEATURES){\n  if(['social-play','club-membership','club-chat','club-activities','clubhouse-ui','ui2-club'].includes(f.id))continue;");
const close='</script>\n<script>\n(()=>{\n const src=document.getElementById(\'gameModule\');';
if(!html.includes(close))throw Error('Game end changed; native lifecycle hook must be reviewed');
if(!html.includes('releaseAll:releaseAllRidingControls'))throw Error('Input release API changed; native lifecycle must be reviewed');
const lifecycle=`
// Generated native lifecycle bridge. Browser source remains unchanged.
window.MeadowlarkNative.attachGame({
 pause(){renderer.setAnimationLoop(null);G.riding.releaseAll();player.breathHold=false;try{if(AC)void AC.suspend().catch(()=>{});}catch{}},
 resume(){G.riding.releaseAll();clock.getDelta();if(!manualStepping)renderer.setAnimationLoop(tick);try{if(AC&&!muted)void AC.resume().catch(()=>{});}catch{}}
});
`;
html=html.replace(close,lifecycle+close);
html=html.replace('</head>','<style>body #installBtn,body #vrBtn,body #netBtn,body #chatFeed,body #chatBar{display:none!important}</style>\n</head>');
await writeFile(path.join(out,'index.html'),html);
// Keep both paths for existing relative links and transferred browser save URLs.
await writeFile(path.join(out,'ranch3d.html'),html);
for(const file of ['index.html','ranch3d.html'])rows.push({path:file,bytes:Buffer.byteLength(html),sha256:hash(html),sourceSha256:originalHtmlHash,transformed:true});
await build({entryPoints:[path.join(mobile,'src/bootstrap.js')],bundle:true,format:'iife',platform:'browser',target:'safari16.4',outfile:path.join(out,'native-bootstrap.js'),minify:false,legalComments:'eof'});
const bootstrap=await readFile(path.join(out,'native-bootstrap.js'));rows.push({path:'native-bootstrap.js',bytes:bootstrap.length,sha256:hash(bootstrap),generated:true});
let revision='unknown';try{revision=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();}catch{}
const status=JSON.parse(await readFile(path.join(mobile,'release-status.json'),'utf8'));
const manifest={schema:1,sourceRevision:revision,mode:'native-development-offline',releaseReady:false,rightsGate:status.blockingAssets,files:rows.sort((a,b)=>a.path.localeCompare(b.path)),bytes:rows.reduce((n,f)=>n+f.bytes,0)};
await writeFile(path.join(out,'bundle-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log('Staged '+rows.length+' files ('+(manifest.bytes/1024/1024).toFixed(1)+' MiB). Approved horse hashes preserved. Development only; release gates remain open.');
