import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const stage=document.getElementById('stage'),status=document.getElementById('status');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(1);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;stage.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#d4dbd0');scene.add(new THREE.HemisphereLight(0xf6f7ff,0x737c65,2.2));const sun=new THREE.DirectionalLight(0xffecd6,3);sun.position.set(-4,7,4);scene.add(sun);const fill=new THREE.DirectionalLight(0xe8eeff,.9);fill.position.set(4,2,-2);scene.add(fill);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.MeshStandardMaterial({color:'#aebca7',roughness:1}));ground.rotation.x=-Math.PI/2;scene.add(ground);scene.add(new THREE.GridHelper(20,40,0x687b5f,0x97a990));
const camera=new THREE.PerspectiveCamera(35,1,.03,100),loader=new GLTFLoader();let asset,body,key='bay-sporthorse',view='side',center=new THREE.Vector3(),height=1.8;
function vertex(i,v){body.getVertexPosition(i,v);return v.applyMatrix4(body.matrixWorld)}
function inspect(){if(!asset)return{ready:false};asset.scene.updateMatrixWorld(true);const p=new THREE.Vector3(),all=new THREE.Box3(),parts=[];asset.scene.traverse(o=>{if(o.isSkinnedMesh){o.skeleton.update();const b=new THREE.Box3();for(let i=0;i<o.geometry.attributes.position.count;i++){o.getVertexPosition(i,p).applyMatrix4(o.matrixWorld);b.expandByPoint(p);all.expandByPoint(p)}parts.push({name:o.name,vertices:o.geometry.attributes.position.count,min:b.min.toArray(),max:b.max.toArray()})}});return{ready:true,id:key,clips:asset.animations.map(a=>a.name),jointCount:body.skeleton.bones.length,finite:body.skeleton.bones.every(b=>b.matrixWorld.elements.every(Number.isFinite)),parts,allMeshMinY:all.min.y,bodyMarker1998:vertex(1998,new THREE.Vector3()).toArray(),bodyMarker1931:vertex(1931,new THREE.Vector3()).toArray()};}
function render(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();const d=height*2.35;camera.position.copy(center).add(new THREE.Vector3(view==='side'?-d:-d*.78,d*.11,view==='side'?0:d*.64));camera.lookAt(center);renderer.render(scene,camera)}
async function load(id){if(asset){scene.remove(asset.scene);asset.scene.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()}})}key=id;asset=await loader.loadAsync('./'+id+'/rest.glb');scene.add(asset.scene);body=null;asset.scene.traverse(o=>{if(o.isSkinnedMesh&&o.geometry.attributes.position.count===16159)body=o});const r=inspect(),part=r.parts.find(p=>p.vertices===16159),b=new THREE.Box3(new THREE.Vector3().fromArray(part.min),new THREE.Vector3().fromArray(part.max));height=b.max.y-b.min.y;center.copy(b.getCenter(new THREE.Vector3()));center.y-=height*.03;status.textContent=`${r.jointCount} native joints · ${r.parts.length} native skin meshes · Standing only`;render();return r}
window.nativeTargetInspect=inspect;window.nativeTargetLoad=load;window.nativeTargetView=v=>{view=v;render();return inspect()};document.getElementById('breed').onchange=e=>load(e.target.value);document.getElementById('side').onclick=()=>nativeTargetView('side');document.getElementById('quarter').onclick=()=>nativeTargetView('quarter');new ResizeObserver(render).observe(stage);try{await load(key)}catch(e){status.textContent=e.message;console.error(e)}
