const fs=require('fs'),path=require('path'),crypto=require('crypto'),QA=require('../../tools/qa-platform.cjs'),K=process.argv[2]||'bay',H=path.join(__dirname,K),O=path.resolve(__dirname,'../../output/native-walk-head-batch',K);
const meta=JSON.parse(fs.readFileSync(path.join(H,'build-summary.json'))),method=JSON.parse(fs.readFileSync(path.join(H,'contact-method.json')));
if(crypto.createHash('sha256').update(fs.readFileSync(path.join(O,'model.glb'))).digest('hex')!==meta.candidateSha256)throw Error('Candidate changed');
const stat=a=>({min:Math.min(...a),max:Math.max(...a),span:Math.max(...a)-Math.min(...a)});
function spectral(a,n){const mean=a.reduce((s,x)=>s+x,0)/a.length;let c=0,s=0;for(let j=0;j<a.length;j++){c+=(a[j]-mean)*Math.cos(2*Math.PI*n*j/a.length);s+=(a[j]-mean)*Math.sin(2*Math.PI*n*j/a.length)}c*=2/a.length;s*=2/a.length;return{n,amplitudeM:Math.hypot(c,s),phaseRadians:Math.atan2(-s,c)}}
function region(a){return{...stat(a),harmonics:[1,2,4].map(n=>spectral(a,n))}}
(async()=>{const browser=await QA.chromium.launch({headless:true,args:QA.gpuArgs()});try{const page=await browser.newPage({viewport:{width:1600,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('http://127.0.0.1:8584/review/native-walk-head-batch/review.html?horse='+K+'',{waitUntil:'load',timeout:90000});await page.waitForFunction(()=>window.retargetInspect?.().ready,null,{timeout:90000});const rows=[];for(let j=0;j<256;j++)rows.push(await page.evaluate(p=>retargetSetPhase(p),j/256));
const curves={};for(const side of ['left','right']){const h=region(rows.map(r=>r[side].joints.head_019.position[1])),t=region(rows.map(r=>r[side].joints.spine_04_012.position[1])),dp=((h.harmonics[1].phaseRadians-t.harmonics[1].phaseRadians+3*Math.PI)%(2*Math.PI))-Math.PI;curves[side]={head:h,trunk:t,n2PhaseDifferenceDeg:dp*180/Math.PI,n2StrideOffset:Math.abs(dp)/(4*Math.PI)}}
let maxHoofDifference=0,maxTrunkDifference=0,maxGroomDifference=0;for(const r of rows){for(const f of ['frontL','frontR','hindL','hindR'])for(const k of ['min','max','center'])maxHoofDifference=Math.max(maxHoofDifference,...r.left.soles[f][k].map((v,c)=>Math.abs(v-r.right.soles[f][k][c])));maxTrunkDifference=Math.max(maxTrunkDifference,...r.left.joints.spine_04_012.position.map((v,c)=>Math.abs(v-r.right.joints.spine_04_012.position[c])));for(let i=0;i<r.right.groom.sample.length;i++)maxGroomDifference=Math.max(maxGroomDifference,Math.hypot(...r.right.groom.sample[i].map((v,c)=>v-r.left.groom.sample[i][c])))}
const contacts={};for(const [f,k]of Object.entries({FL:'frontL',FR:'frontR',HL:'hindL',HR:'hindR'})){const a=rows.filter(r=>((r.phase-method.footMasks[f].offset+1)%1)<method.stanceFraction);contacts[f]=stat(a.map(r=>r.right.soles[k].min[1]))}
for(const view of ['side','quarter']){await page.evaluate(v=>retargetSetView(v),view);for(let j=0;j<16;j++){await page.evaluate(p=>retargetSetPhase(p),j/16);await page.screenshot({path:path.join(O,`head-${view}-${String(j).padStart(2,'0')}.png`)})}}
const finite=rows.every(r=>[r.left,r.right].every(p=>p.bones===677&&p.allBoneTransformsFinite&&p.finite&&Number.isFinite(p.groom.minY))),seams=await page.evaluate(()=>retargetClipSeams());const summary={label:meta.label,targetHeadSpanM:meta.targetHeadSpanM,candidateSha256:meta.candidateSha256,sourceSha256:meta.sourceSha256,phaseCount:rows.length,finite,errors,landmarks:'World origins head_019/spine_04_012; proxies, not the paper optical markers',curves,maxHoofWorldDifferenceM:maxHoofDifference,maxTrunkWorldDifferenceM:maxTrunkDifference,stanceContacts:contacts,wholeBodyFloor:stat(rows.map(r=>r.right.bounds.min[1])),groomVertexCount:rows[0].right.groom.vertices,groomSampleCount:rows[0].right.groom.sample.length,maxGroomChangeFromCurrentWalkM:maxGroomDifference,originalManeTailChannelsPreserved:true,sourceTackPreserved:true,limitation:'Trunk n4 dominance and source high carried posture unchanged. This only tests neck/head motion and contact preservation.',noMotionOrProductionApproval:true};fs.writeFileSync(path.join(O,'browser-report.json'),JSON.stringify({summary,rows,seams},null,2)+'\n');fs.writeFileSync(path.join(H,'qa-summary.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary,null,2));if(errors.length||!finite||maxHoofDifference>1e-6||maxTrunkDifference>1e-6||Math.abs(curves.right.n2PhaseDifferenceDeg)<175||Math.abs(curves.right.head.span-meta.targetHeadSpanM)>.001)throw Error('Head pilot gate failed');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
